server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hr?characterEncoding=UTF-8&serverTimezone=UTC
    username: eandr
    password: e&r

  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    hibernate:
      ddl-auto: validate
    show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    root: error
#    org.springframework: DEBUG
#  config=classpath: logabck.xml